fisshy/react-scroll

modules/mixins/Helpers.js
Add offset prop to Link-element for controlling scrolling offset. Value can be positive or negative.
=> add support for setting scroll offset

build/npm/lib/mixins/Helpers.js, modules/mixins/Helpers.js
Addresses https://github.com/fisshy/react-scroll/issues/2 @fisshy
=> Pass event in to click handler. Closes #2.

modules/mixins/Helpers.js
* Take offset into account for scroll spy
* Add offset to Scroll mixin proptypes
=> Fix scroll spy offset bug

README.md, modules/components/Button.js, modules/index.js
Currently there is only link support that will handle the users clicking and scrolling to an element. I have added support for using html input elements as buttons. This will allow the user to click on a button and go to an element.
=> Add button support

modules/components/Link.js, modules/mixins/animate-scroll.js, modules/mixins/cancel-events.js, modules/mixins/scroll-spy.js
Defines an optional `activeClass` that can be passed to `Link`
- reasoning: We use `m-active` instead of `active` for modifier classes
Ensures (hack, trail & error) component can be rendered server side
Couldnt find any tests or other quick ways to verify 
Tried to stay within codestyle as much as possible
=> Define optional active class

modules/mixins/Helpers.js, package.json
* move dependencies to update dependencies and update versions
* remove getDOMNode
=> Get ready for 0.14

build/npm/lib/mixins/animate-scroll.js
[Issue 55](https://github.com/fisshy/react-scroll/issues/55)
Somewhat related StackOverflow thread for reference:
[http://stackoverflow.com/questions/9677985/uncaught-typeerror-illegal-invocation-in-chrome](http://stackoverflow.com/questions/9677985/uncaught-typeerror-illegal-invocation-in-chrome)
=> Possible Resolution to Issue 55

modules/mixins/Helpers.js, modules/mixins/scroll-spy.js
Fixes fisshy/react-scroll#57
Fixes fisshy/react-scroll#50
=> Refactor scroll-spy as scroll event proxy

build/npm/lib/mixins/animate-scroll.js, modules/mixins/animate-scroll.js
see http://stachowski.me/jquery-ie-error-invalid-calling-object/
=> Rename the requestAnimationFrame helper so the library works in ie/edge

modules/mixins/Helpers.js
In order to work with transition effects I had to introduce a delay property. My use case is this:
1. User clicks on react scroll link
2. react scroll element receives new height
3. React scroll calculates offset and scrolls to the resized container element
=> introduce delay property

.gitignore, examples/basic/app.js, modules/__tests__/animate-scroll-test.js, modules/mixins/Helpers.js, modules/mixins/animate-scroll.js
Allowing to pass a function as the duration prop.
Function is called when the animation is starting to determine the duration of the animation based on the current deltaTop.
=> Dynamic animation time

modules/mixins/Helpers.js
=> do not fail when there is no element to scroll to

modules/mixins/Helpers.js
fixes #94 unused props warning
https://fb.me/react-unknown-prop
=> Don't pass all props / new 15.2 warning fix

modules/mixins/animate-scroll.js
In reference to [this comment](https://github.com/fisshy/react-scroll/pull/33#issuecomment-230987378) by @cersfeld
=> Gets container when calling scrollToBottom and scrollMore

modules/mixins/Helpers.js
switched 'const' to 'var', phantomjs is throwing an error because of it.
=> ES6 where it shouldn't be

modules/mixins/Helpers.js
This was causing some problems for our code validators :)
=> Fixes missing semicolon

modules/mixins/scroll-spy.js
=> Fix scroll-spy punctuation error

modules/mixins/scroller.js
=> Fixes scrollTo not working

README.md
"Its" is the possessive pronoun. "It's" is a contraction of "it is".
=> Correct homophone.

README.md, build/npm/lib/mixins/Helpers.js, modules/mixins/Helpers.js
I missed this callback function because I need to change the Link's inline style inside the component.
=> onSetInactive callback function added to Link

examples/basic/app.js, modules/components/Button.js, modules/components/Element.js, modules/components/Link.js, modules/mixins/Helpers.js, package.json
> #195 
1. Use prop-types package to fix the first warning 
2. Use class Component to fix the second warning 
- I didn't use mocha to test it , but the examples can run without warning and errors
=> Use the prop-types package and class Component to fix the React warning

README.md
=> replace "directive" with "component"

modules/__tests__/animate-scroll-test.js, modules/mixins/Helpers.js, modules/mixins/animate-scroll.js, modules/mixins/scroller.js, package-lock.json, package.json
Had requirement to pass node as cotainter not just ID. If both 'containerId' and 'container' props are passed, the former takes precedence
=> Had requirement to pass node as cotainter not just ID. If both 'containerId' and 'container' props are passed, the former takes precedence

gulpfile.js, package.json
Reverts fisshy/react-scroll#232
=> Revert "Allow installing package directly from Github"

package.json
Addresses #238 
Submitted with employer's consent.
=> Use transform-object-assign

README.md
#82 added ability to specify animation duration as a function. This is really a brilliant idea!
But I had to browse through the source code in order to figure that.
I think it would be nice to mention this feature in the docs.
=> Extended the 'duration' prop description in README

package.json
=> Allow React 16 as a peer dependency

README.md
This pull request is regarding issue 
#[315](https://github.com/fisshy/react-scroll/issues/315)
=> live expamles added

modules/mixins/animate-scroll.js
https://github.com/fisshy/react-scroll/issues/384
=> Animated scroll time not consistent  #384

modules/mixins/Helpers.js, modules/mixins/scroll-element.js
=> Replace UNSAFE_ lifecycle methods

modules/mixins/utils.js
added function for calculating the offset and fixed the offset of the calculation for the element
=> added function for calculating the offset and fixed the offset of the calculation for the element

README.md
Cleaned up the README a bit. Huddled around single quotes and lining up those equal signs. Also dropped unnecessary line breaks and added in some line breaks to make the raw file more readable. Also noticed tabs in a few spots.
Cool lib, keep up the great work!
=> docs: cleanup inconsistencies

examples/with-hash/app.js, modules/__tests__/link-test.js, modules/mixins/scroll-hash.js, modules/mixins/scroll-link.js, modules/mixins/utils.js
Hash is always pushed to history and saved , Added a option for user to opt for the same.
=> Hash History save issue triggering weird back button issues

README.md
follow up to #429 
Thank you for the reminder @LeoAmeneiros !
=> Update README with horizontal scrolling instructions

README.md
Deleted `smooth` duplicate row in [Props/Options section](https://github.com/fisshy/react-scroll#propsoptions)
=> Deleted duplicate smooth row in README

modules/components/Element.js
=> Fix: #538 Remove Element's name attribute

modules/mixins/scroll-link.js, modules/mixins/scroll-spy.js
=> fix: remove record before scroll-link unmount

README.md
Gen AI chatbot for react-scroll. Will help Developers understand this repository better. You can ask for code examples, installation guide, debugging help and much more.
=> Add React-Scroll AI Botin Readme
