fisshy/react-scroll

- build/npm/package.json
- package.json
Allows for React v0.13.x while maintaining v0.12.x support. Tested on my machine on a few modern browsers and works well.
> Provide more flexible React peer dependency range

- modules/mixins/Helpers.js
* The top/height can sometimes always be 0, I believe due to the order
in which the components are added to the page.
* Calculate top/height the first time the func is called
> Fix issue where top/height always 0

- modules/components/Link.js
- modules/index.js
- modules/mixins/Helpers.js
- modules/mixins/animate-scroll.js
- modules/mixins/scroll-spy.js
- modules/mixins/scroller.js
* If scroll-spy is enabled and the component is unmounted the scroll
events will still hang around and attempt to set state.
* The design should probably be changed to not use globals (a service
instead perhaps?), though this is a quick fix.
> Fix scroll-spy events leaking after component unmount

- modules/mixins/Helpers.js
Seems unmount() on the scrollSpy was never called? It gave errors in Safari when scrolling.
> unmount scrollSpy when unmounting

- modules/mixins/Helpers.js
- modules/mixins/scroll-spy.js
- modules/mixins/scroller.js
It seems I broke the scroll-spy functionality somewhat with my previous pull-request... This should fix that. Now, active-state should work when mounting/unmounting between instances.
> Fix for broken scroll-spy

- modules/mixins/Helpers.js
Replaced deprecated React#getDOMNode with React.findDOMNode which caused an error
``Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined``
Error occurs when using React via ES6 class syntax.
Related note from [React documentation](https://facebook.github.io/react/blog/2015/03/10/react-v0.13.html)
> Added new top-level API React.findDOMNode(component), which should be used in place of component.getDOMNode(). The base class for ES6-based components will not have getDOMNode. This change will enable some more patterns moving forward.
> Replaced deprecated React#getDOMNode

- build/npm/lib/mixins/Helpers.js
- modules/mixins/Helpers.js
Hi fisshy - thanks for the library! It's quite useful.
Currently, when you scroll to a Scroll Element, the corresponding Scroll Link <A> tag is given the class "active". However, I've run into a couple scenarios now where, due to my CSS/HTML structure, the *parent* element of the link (usually a LI tag) needs to get the "active" class, not the link itself. In particular, the nav in Bootstrap expects the LI, not the A, to be "active" in order to render correctly.
So I've added a simple hook which allows you to define an `onSetActive` callback on Scroll Link components. This way, when the link becomes active, I can respond to it in the parent component and add the "active" class to the proper parent. I'm sure it has other uses too.
Hope it's helpful! Thanks,
-d
> add optional callback onSetActive, called when active Scroll Link is set

- modules/mixins/Helpers.js
There is an issue with active link. When we scroll up to some section – correspondent link becomes active, but when we scroll away from that section – link still remains active (unless some other link become active).
Also ``top`` and ``height`` variables renamed to more consistent ``elemTopBound`` and ``elemBottomBound`` correspondently.
> Inactivates link when Y is out of Element bounds

- modules/mixins/Helpers.js
I'm working on a project now that uses React 0.13.3, and it's having trouble with the findDOMNode function. I've found that this change fixes my issues, though I'm not sure if it'll make react-scroll scream deprecation warnings once 0.14 releases.
I suspect this may fix what's behind this issue as well: https://github.com/fisshy/react-scroll/issues/27
> update helper to use getDOMNode if available to be compatible with earlier React versions

- build/npm/lib/mixins/animate-scroll.js
- modules/mixins/animate-scroll.js
animateScroll() assumes that there's a timestamp, so the requestAnimationFrame setTimeout fallback needs to add that. This enables scrolling in IE9.
> Add timestamp to requestAnimationFrame fallback

- modules/mixins/Helpers.js
- modules/mixins/scroll-spy.js
Branched from fisshy/react-scroll#58
Fixes fisshy/react-scroll#49
Caching `<Element>` bounding boxes causes functionality to break when the viewport is resized. It's faster to cache, [but maybe not _that_ much faster](https://jsperf.com/getboundingclientrect-cached). Seems reasonable to give the browser the responsibility of bbox caching until it proves to be too slow. This also somewhat aligns with Reacts official recommendation of computing the latest values on the fly (in `render` methods)
> Viewport resize

- modules/mixins/scroller.js
Use accessor to get scrolling element.
It helps to control returning element. For example to find element in DOM by anchor/id.
> Use accessor method in scroller

- .gitignore
- build/npm/lib/mixins/Helpers.js
- build/npm/lib/mixins/scroller.js
- examples/basic/app.js
- modules/__tests__/events-test.js
- modules/__tests__/page-test.js
- modules/components/DirectLink.js
- modules/index.js
- modules/mixins/Helpers.js
- modules/mixins/direct-scroller.js
- modules/mixins/scroller.js
- tests.webpack.js
Here is a little modification of Helpers.Scroll to allow use custom scroller.
This can helps to find element by id/anchor in some cases (see an example App)
With tests.
ex https://github.com/fisshy/react-scroll/pull/69
> Direct link to not registered elements

- README.md
- modules/__tests__/animate-scroll-test.js
- modules/__tests__/events-test.js
- modules/mixins/animate-scroll.js
This PR adds 2 new methods:
- **scrollTo**
Makes it super easy to scroll to an absolute position from the top
- **scrollMore**
Allows scrolling to a relative position from the current scroll position. 
The reason I didn't like to use the provided animateTopScroll, is because it behaves as scrollMore rather than scrollTo. If one needs to scroll to an absolute position from the top, it needs to do the math at the implementation level, which is not that nice.'
I'm also thinking of adding a **scrollToBottom** method, to avoid the above mentioned math calculations when you need to scroll to bottom.
> Add scrollTo(position), scrollMore(px) and scrollToBottom() methods

- package.json
`modules/mixins/animate-scroll.js` requires `object-assign`, but the
relevant package is not in `package.json`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/fisshy/react-scroll/73)
> Add missing dep `object-assign`

- README.md
DirectLink was missing as a component variable in the README.
> Added missing DirectLink variable

- modules/mixins/Helpers.js
Added isDynamic prop that will recalculate the element coordinates. Our web page has dynamic components like accordions. Incorrect navigation items are being highlighted after expanding the accordion for example.
> Expose isDynamic prop to recalculate the element coordinates

- README.md
Other options are explained well elsewhere, and aren't needed to illustrate scrolling with optional container.
> Clarifies example with container

- build/npm/lib/mixins/Helpers.js
- modules/mixins/Helpers.js
BUGFIX: while 'elemTopBound' is decimal, the 'isInside' would be false, and no 'ScrollLink' would be 'active';
> BUGFIX: fix the bug when 'elemTopBound' is decimal

- modules/mixins/scroll-spy.js
Fixes `Cannot read property 'length' of undefined` js error when scrollSpyContainer is missing spyCallbacks
> Handle length of undefined when scrollSpyContainer is missing spyCallbacks

- modules/mixins/Helpers.js
Fixes `Warning: Unknown prop `absolute` on <a> tag. Remove this prop from the element.`.
> Add `absolute` to protoTypes

- README.md
- modules/mixins/Helpers.js
Looks like `onSetActive` prop has been added in scope of https://github.com/fisshy/react-scroll/pull/28 to detect whenever `<Link>` is marked as active.
It has never been added to `propTypes` as well as documented.
This PR documents new prop in README.md as well as adds this `onSetActive` prop to propTypes so that it can be defined when creating a `<Link>`.
> Adds missing onSetActive prop to propTypes.

- build/npm/lib/mixins/Helpers.js
- modules/mixins/Helpers.js
I need to change an `Element`'s name instead of destroying it and creating it again, but when I try to do this the `Element` is not registered again.
The solution that I found was to add a `componentWillReceiveProps` function to the `Element` in order to register it again when the name changes.
> When an Element's name is changed, the element in not registered again

- build/npm/lib/mixins/Helpers.js
- build/npm/lib/mixins/scroll-spy.js
- modules/mixins/Helpers.js
- modules/mixins/scroll-spy.js
In some cases I need to unmount some Links after the new page is displayed with the new Links.
The problem is that the "unmount" method (scroll-spy.js line 79) just removes all spyCallbacks from the scrollSpyContainers instead of removing the specific callback of the element that I try to unmount.
> Spy doesn't work when new Links are mounted before an old one unmounts

- build/npm/lib/mixins/animate-scroll.js
- modules/mixins/animate-scroll.js
Hello. Sorry for my English.
Use your unit to scroll to the 
`<div id="container"><Element name="element"> content </Element></div>`
and 
`Scroll.scroller.scrollTo('element', {containerId: 'container'});`
There is a problem if we go for the first time, everything works fine, but if the walk on the site, and again go to the page, nothing happens. I found out it's because of what **__containerElement** has been announced, and the second time he has not appropriated. Accordingly, scroll to the item did not work.
See my solution to the problem, and accomplish your goal, what you think about it.
Thank you.
> hotfix/set-container - fixed method setContainer in animate-scroll

- README.md
The value for the `delay` property represents milliseconds (not seconds).
> Fix `delay` documentation

- package.json
Make react and react-dom devDependencies so that installing react-scroll will not generate complaints about differing versions of react, or possibly fail altogether if using shrinkwrap.
> Move react and react-dom to devDependencies

- README.md
Added containerId prop to the scrollTo example for clearer documentation (wasted some time on it myself before I read the source code and realized what I should do :( )
I know this is part of the Link props and should be obvious, but apparently it isn't that obvious...
> Add containerId to the README example of ScrollTo Element function

- package.json
This package doesn't work at all with [last package.json change](https://github.com/fisshy/react-scroll/commit/fab73af07ee11bdbaa2e016474cd94a7cb0fd645). Because the project is built under `build/npm/lib` folder. It should be under `build/npm/modules` to work.
> Update build folder for npm

- examples/webpack.config.js
Fix the error with build script:
"
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
- configuration.output.path: The provided value "examples/build" is not an absolute path!
"
> Fix the error related with absolute path

- modules/components/Button.js
- modules/components/Element.js
- modules/components/Link.js
Fixes the following warning in React 15.6 and above:
“Warning: Accessing factories like React.DOM.a has been deprecated and will be removed in v16.0+. Use the react-dom-factories package instead.  Version 1.0 provides a drop-in replacement. For more info, see https://fb.me/react-dom-factories”
> Use JSX instead of React DOM factories to fix React warning in >= 15.6

- modules/components/Element.js
- modules/mixins/Helpers.js
This allows for testing with jsdom and jest
See: https://github.com/fisshy/react-scroll/issues/185
Another way to solve this is using `bindNode` (the way this person did: https://github.com/Baransu/react-scroll/commit/5f1708a7dbe0586500c67df1241344c32bb8dd9c)
> [Change] Use `rel` instead of `findDOMNode`

- modules/mixins/animate-scroll.js
There are typos in `getAnimationType` that cause the wrong easing to be selected.
The existing code had been mapping from `options.smooth` to the appropriate easing function from `smooth.js`. The problem is that some of the mappings were incorrect.
My proposed solution is to do a simple lookup directly on the object exported from `smooth.js`. This reduces code, and increases maintainability by creating one source of truth for the smooth options.
The new code should behave equivalently to the old with one slight exception: `'defaultEasing'` can now be passed to access that easing directly. This shouldn't have much effect since passing `'defaultEasing'` before (or even `'foobar'`) would have still resulted in `defaultEasing` being used. The only concern is that now people might come to …
> fix: typos in getAnimationType

- modules/__tests__/scroll-cancellation-test.js
- modules/mixins/animate-scroll.js
- modules/mixins/cancel-events.js
Fixes #269 
The first commit dea9cb3 is the failing test that describes the issue in #269. For some reason, it only fails (as it should) when run alone via `describe.only`; it somehow passes when run with the rest of the tests. I suspect there is some poor test isolation going on with the rest of the test suites; maybe a test suite is mutating some top level variables without cleaning up...
The second commit b7741ad is the fix. We simply bind the event listener once, during module initialization time, instead of binding new event listeners every scroll invocation.
> Simplify scroll event cancellation

- modules/mixins/Helpers.js
Return false for certain lifecycle hooks when DOM is unavailable.
> Support server side rendering. Fixes #88

- modules/index.js
Before, a scroller.js was exported as a "scroller", but now it's imported as a "scroll" and it breaks all of the old code.
> Change scroller.js exported name

- modules/mixins/scroll-link.js
Currently when scrolling with `spy` enabled, all links are constantly re-rendered instead of just the ones whose `active` state is changing. This PR fixes that by making `ScrollLink` a `PureComponent`. The following animations show which links are being re-rendered.
Before:
After:
> Prevent re-rendering all links on every scroll tick

- modules/mixins/scroller.js
It can be useful when we have few elements and need to scroll to first of them. Right now as I know, `react-scroll` can't handle this situation except elements with the name attribute (so it can be one of the form elements) or by handling complex logic on the client side to keep tracking of multiple ids of elements.
> Refer to the element by className

- modules/mixins/scroll-spy.js
- package.json
Change eventThrottler to use lodash throttle instead of custom throttle
implementation to fix issues with performance degradation when adding
more elements and links in the same browser session.
Fixes #308
> Use lodash throttle

- modules/mixins/utils.js
fixed position calculation top for element when container position is set fixed.
offsetTop is deprecated parameter and counting relative to the parent.
getBoundingClientRect().top finds the correct distance from the top of the screen.
So the element can be nested deeply and it will work correctly.
> fixed calculation position top for element

- README.md
As per:
> v1.3.0
Remove directlink, now just use Link.
> Removed mention of DirectLink component

- modules/mixins/scroll-link.js
First of all, thanks for the amazing library!
There is a bug, that when a active component gets unmounted and mounted
again, the state won't be set to active, due to wrong caching.
Repro: 
1. https://codesandbox.io/s/yv372noqjv
2. "Go to first element inside container" is active
3. click on button "Show / Hide" to unmount the component
4. click on button "Show / Hide" to mount the component
5. "Go to first element inside container" not active anymore
In this demo you can see the fixed version.
https://codesandbox.io/s/qkjj5z8wq
Cheers
Thomas
> Fix for wrong activeLink when component remounts

- modules/mixins/scroll-hash.js
- package-lock.json
When scrolling using hash I noticed these warnings in my console.
After a little debugging I found that the scroll-hash module, updates the hash even when the new hash is the same as the old hash. 
This PR compares the current hash to the incoming hash and if they are the same, does nothing.
I am not really all that great with the react 16 profiling in Chrome, but considering the warning, I think this will improve performance at least in some cases.
> only update the hash if the new hash is different than the current hash

- modules/mixins/Helpers.js
- modules/mixins/scroll-element.js
With the latest version of react (16.9.0), a warning is being displayed whenever a deprecated lifecycle method is used. This PR is a quick fix which renames the lifecycle into UNSAFE_* which is still supported by react. This will remove the warnings but not totally fix the deprecated lifecycles. This is a stop-gap solution.
> Renamed deprecated react lifecycles to UNSAFE_*

- modules/mixins/animate-scroll.js
- modules/mixins/scroller.js
Currently react-scroll's `animateScroll` only has an implementation for the `end` event. Here we add the `begin` event to `animateScroll` and and relocate the implementation within `scroller` to avoid duplicate calls.
This aims to solve the issue mentioned in #327 & #391
> Ensure 'begin' event fires on all scroll events

- gulpfile.js
- package-lock.json
- package.json
Hey, this PR updates Gulp to version 4, fixing the following error when running `npm run build`.
```sh
...
modules/mixins/utils.js -> build/npm/modules/mixins/utils.js
fs.js:36
} = primordials;
^
ReferenceError: primordials is not defined
at fs.js:36:5
```
This error occurs due to Node.js 12 (or above) and Gulp 3. For more info, check [this Stack Overflow question](https://stackoverflow.com/questions/55921442/how-to-fix-referenceerror-primordials-is-not-defined-in-node).
After upgrading to Gulp 4, the error was fixed, and the build has run successfully.
> chore: update Gulp to version 4

- package.json
Otherwise we get this error when running `npm install` using React 17.x:
```
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.5.4 || ^16.0.0" from react-scroll@1.8.1
npm ERR! node_modules/react-scroll
npm ERR!   react-scroll@"^1.8.1" from the root project
```
> Update peer dependencies for react 17.x

- README.md
- modules/mixins/utils.js
In certain instances where an Element is not a direct descendant of the containerElement, it's offsetTop would be with respect to its parent not the containerElement. A use-case is as follows: 
```html
<div id="scrollable"> 
<div>...</div>
<div id="container-1"> 
<Element name="element-1">...</Element>
<Element name="element-2">...</Element>
</div>
<div id="container-2"> 
<Element name="element-3">...</Element>
<Element name="element-4">...</Element>
</div>
</div>
```
Invoking
```javascript
scroller.scrollTo("element-x", {
...,
containerId: "scrollable"
});
```
would probably scroll back to the top (as was in my case) since element-x's offsetTop would be with respect to container-y (it's parent) and not "#scrollable". Setting containerId (in scrollTo) to the corresponding container of …
> fixing scrollOffset

- modules/mixins/scroll-spy.js
**Problem**:
Multiple scrollSpy.unmount() calls may occur on same Link due to component tree rebuild. Subsequent calls will try to remove already non-existing spyHandler. In this case .indexOf(spyHandler) will return -1 and .splice(-1, 1) will cause unwanted removal of last spyHandler in list.
Same with setState handlers.
**Solution**
Add extra check to make sure spyHandler and setState are in lists
> fix: prevent unexpected spy callback removal on multiple unmount calls

- modules/mixins/animate-scroll.js
- modules/mixins/passive-event-listeners.js
I encountered an issue where event listeners were being registered multiple times.
I discovered that when calling scrollTo-related functions in the `animate-scroll` module, event listeners were being registered through the `subscribe` method. 
There was no logic to remove registered events or check for duplicates, resulting in event listeners being registered multiple times. 
I have thought of the simplest solution: preventing duplicate registrations by using the name of the listener function passed as a parameter to the `addPassiveEventListener` function as a key. 
It is important to note that you should pass a named function with a **unique name as the listener parameter**, rather than an anonymous function.
Fix for #451
<hr/>
- As-is
<br/>
<br/>
- To-be
> Preventing duplicate event listener registrations

- README.md
**Description:**
This Pull Request encompasses a series of enhancements aimed at improving the codebase and documentation of our project. The key modifications include the conversion of class components to functional components, utilizing the latest features and best practices in React development. Additionally, the README file has been updated to reflect these changes, providing users and contributors with more accurate and up-to-date examples.
- **Convert Class Components to Functional Components:** All class components in the examples have been refactored to functional components, leveraging hooks and other modern React features.
- **Update README Examples:** The examples provided in the README have been revised and updated to align with the latest React best practices and the changes …
> Modernize README Examples and Convert Components to Functional #511

- modules/__tests__/button-test.js
- modules/components/Button.js
@fisshy 
fix #156 
The current Button component is implemented using the `<input>` tag, and when children elements are included, React throws the following error:
```
Uncaught Error: input is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.
```
To resolve this issue, I suggest changing the implementation from using an `<input>` tag to a `<button>` tag.
And I added test code for the updated Button component.
> Fix children rendering issue in Button component

- modules/mixins/cancel-events.js
`mouseWheel` event is deprecated and is not compatible with Firefox. Thus, on Firefox when scrolling is happening and user wants to stop the scrolling with mouse wheel, scrolling doesn't cancel. All other events seems to be working normally.
https://developer.mozilla.org/en-US/docs/Web/API/Element/mousewheel_event
> change mouseWheel event in cancel events
